<?php

namespace Ais\MahasiswaProfileBundle\Repository;

/**
 * MahasiswaProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MahasiswaProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
